[build]
  publish = "."
  command = "bash ./generate-supabase-config.sh"

[headers]
  [[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer-when-downgrade"
  Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
